name: chessgrinder_local
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "12345:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "9797:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./containers/var/lib/postgresql/data:/var/lib/postgresql/data
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
